### ISSUE TITLE
error 400

### ISSUE THREAD

**Issue by dadude1** [53845714nF/vuln2pve#1]
hello i am trying to use this script but i am receiving the following errors. 

400 Parameter verification failed.
name: invalid format - value does not look like a valid DNS name

vmid: invalid format - value does not look like a valid VM ID

qm create <vmid> [OPTIONS]
 Fail to create VM

**Comment by 53845714nF** [comment]
Can you tell me which URL you used? The script tries to make a name out of the URL. I could imagine that I have to modify this.

If you have found the error yourself, please send me the pull request.

Best regards

**Comment by 53845714nF** [comment]
Do you have any more information for me? Otherwise, I will close the issue in the next 14 days.

**Comment by 53845714nF** [comment]
As no additional information is available, I am closing the issue. It can be reopened when more information is provided.
